
//TODO: remove unused strings

Lazarus.locale.strings = Lazarus.locale.strings || {};

Lazarus.locale.strings['en'] = {

  "app.version": "unknown",
  "app.build": "unknown",
  "app.platform": "unknown",
  "app.updateChannel": "unknown",
  "app.name": "Lazarus: Form Recovery",
  "app.email": "lazarus@EXAMPLE.com",
  
  "url.syncInfo": "http://getlazarus.EXAMPLE.com/Sync",
  "url.syncFAQ": "http://getlazarus.EXAMPLE.com/Lazarus-3-FAQ",
  "url.syncSecurity": "http://getlazarus.EXAMPLE.com/Sync_Security",
  "url.proVersion": "http://getlazarus.EXAMPLE.com/Buy-Lazarus-Pro",
  "url.mainSite": "http://getlazarus.EXAMPLE.com",
  "url.contactUs": "http://getlazarus.EXAMPLE.com/Special_Contact",
  "url.passwordHelp": "http://getlazarus.EXAMPLE.com/Lazarus-3-FAQ#Lost-Password",
  
  "generic.cancel": "Cancel",
  "generic.close": "Close",
  "generic.minutes": "minutes",
  "generic.hours": "hours",
  "generic.days": "days",
  "generic.or": "or",
  "generic.error.msg": "Sorry, an error occurred and Lazarus was unable to complete the action",
  
  "elapsed.never": "never", 
  "elapsed.none": "now", 
  "elapsed.second": "{time} second ago", 
  "elapsed.seconds": "{time} seconds ago", 
  "elapsed.minute": "{time} minute ago", 
  "elapsed.minutes": "{time} minutes ago", 
  "elapsed.hour": "{time} hour ago", 
  "elapsed.hours": "{time} hours ago", 
  "elapsed.day": "{time} day ago", 
  "elapsed.days": "{time} days ago", 
  "elapsed.week": "{time} week ago", 
  "elapsed.weeks": "{time} weeks ago", 
  "elapsed.month": "{time} month ago", 
  "elapsed.months": "{time} months ago", 
  
  "header.link.buyLazarusPro": "Get Lazarus Pro",
  
  "disable.domain": "Disable Lazarus on this site",
  "disable.domain.tooltip": "Disable Lazarus for all pages on '{domain}'.",
  "disable.domain.confirm": "Are you sure you want to disable Lazarus for all pages on '{domain}'? \nThis will also remove all forms saved from {domain}.",
  "disable.domain.success": "Lazarus has been disabled for all pages on '{domain}'. \nTo re-enable any site remove it from the disabled sites list in the Lazarus options.\n\nDo you also want to remove any currently existing forms saved from '{domain}'?",
  "disable.domain.removeForms.confirm": "Lazarus has been disabled for all pages on '{domain}'. \nTo re-enable any site remove it from the disabled sites list in the Lazarus options.\n\nDo you also want to remove any currently existing forms saved from '{domain}'?",
  "disable.domain.removeForms.success": "All saved forms for '{domain}' successfully removed.",

  "disableOnSite.title": "Disable Lazarus",
  "disableOnSite.question": "Are you sure you want to disable Lazarus for all pages on <strong>{disableOnSite.site}</strong>?",
  "disableOnSite.removeExistingForms": "Also remove all existing forms saved from {disableOnSite.site}.",
  "disableOnSite.btn.disable": "Disable Lazarus on {disableOnSite.site}",
  
  "login.title": "Password Required",
  "login.enterPassword": "Enter Your Lazarus Password",
  "login.btn.login": "Login",
  
  "menu.loading.saved.forms": "Fetching saved forms...",
  "menu.loading.saved.text": "Fetching saved forms...",
  "menu.logout": "Logout",
  "menu.logout.tooltip": "Logout to require a password before being able to restore forms again",
  "menu.no.saved.forms": "No saved forms found",
  "menu.no.saved.text": "No saved text found",
  "menu.enter.password": "Enter password...",
  "menu.enter.password.tooltip": "You'll need to enter your Lazarus password before you can recover this form",
  "menu.options": "Lazarus Options...",
  
  //options dialog
  "options.title": '{app.name}: Options',
  "options.versionInfo": '{app.platform} {app.version} {app.updateChannel}',
  "options.versionInfoFull": '{app.platform} {app.version} {app.updateChannel} (build {app.build})',
  "options.about": "About Lazarus 3",
  "options.about.html": "<p>Lazarus 3 is a complete cross-browser (Firefox/Chrome/Safari) re-write of our famous Lazarus Form Recovery for Firefox. It's faster, it's easier to use, and it works on more web-forms than ever! We hope you'll love it as much as we do.</p>",
  "options.contact": "Contact Us",
  "options.contact.html": '<p>Send us feedback, bug reports and feature requests <a href="{url.contactUs}">via this form<a>, or via email to <a href="mailto:{app.email}?subject=Lazarus%203%20for%20{app.platform}">{app.email}</a></p>',
  "options.debug": 'Debugging',
  "options.debugMode": 'Log Level',
	"options.debugMode.1": "Suppress all messages",
	"options.debugMode.2": "Log errors",
	"options.debugMode.3": "Log errors and warnings",
	"options.debugMode.4": "Log errors, warnings and messages",
	"options.general": "General",
  "options.password": "Lazarus Password",
  "options.password.title": "Use a Lazarus password to protect your data",
  "options.password.change": "Change password",
  "options.password.remove": "Remove password",
  "options.password.resetLabel": "Forgotten your old password entirely? Sadly, for your security, Lazarus does not keep any copies of it, however you can chose to:",
  "options.password.reset": "Delete previously saved forms and start again",
  "options.password.current": "Old password",
  "options.password.new": "Enter password",
  "options.password.confirm": "Re-enter password",
  "options.password.save": "Save password",
  "options.general.title": "Other Options",
  "options.whatToSave": "What to save",
  "options.expireForms": "Data Expiry",
  "options.expireForms.info": "How long should we keep your web-form data for?",
  "options.expireForms.moreInfo": "We noted with Lazarus 2 that heavy web-form users who did not expire their data often ended up with a very large database that caused performance problems and javascript timeouts, particularly during version upgrades, and while searching encrypted data. For the moment we have limited the time form data can be saved to two weeks.",
  "options.expireForms.intervalTooLarge": "Forms can only be kept for a maximum of {days} days",
  "options.disabledDomains": "Disabled Sites",
  "options.disabledDomains.info": "To re-enable a site, remove it from the list",
  "options.disabledDomains.none": "To disable Lazarus on a website, use the Lazarus Context Menu. Sites can be re-enabled later by returning here.",
  "options.disabledDomains.delete": "Remove",
  "options.security": "Security",
  "options.security.title": "Password",
  "options.database": "Database",
  "options.database.title": "Database Options",
  "options.databaseRebuilt": "Database rebuilt!",
  "options.experimental": "Experimental",
  "options.tooltip": "Edit your Lazarus options",
	"options.rebuildDatabase": "Delete all saved forms and rebuild the database",
	"options.rebuildingDatabase": "Rebuilding database...",
	"options.savePasswords": "Save webform password field data",
	"options.savePasswords.info": "Please note: storing password field data in the Lazarus database is <strong>not</strong> secure unless you <strong>set a Lazarus password first!</strong>", 
	"options.saved": "Options saved.",
	"options.updates": "Updates",
	"options.updates.checking": "Checking for updates...",
	"options.updates.ok": 'Lazarus is up to date (<span class="version-info">{options.versionInfo}</span>)',
	"options.updates.newVersionAvailable": '<a href="{url}" title="Install it now">A new version of Lazarus ({version} {channel}) is available!</a>',
	"options.updates.error": "An error occured when checking for updates.",
	"options.reset": "Reset to defaults",
	"options.reset.confirm": "Are you sure you want to reset all of your settings to their default values and remove all saved forms from the database?",
	"options.preferencesReset": "Preferences reset",
	"options.resettingPrefs": "Resetting preferences...",
  
  "options.securityAndPrivacy": "Security and Privacy",
  "options.securityAndPrivacy.info": "What you type into web-forms is often private information. Once you have set a Lazarus password your data will be securely encrypted and unrecoverable until you have entered your password.",
  
	"options.sync": "Sync",
	"options.sync.title": "Backup and Sync (Beta)",
  "options.sync.info": '<h4>Keep your form data even more securely backed up!</h4><p>Lazarus Sync <b>continually backs up</b> your webform data onto an offsite server so it can be restored even after a hard drive crash or<br> re-installing your browser. All your data is <a href="{url.syncSecurity}" target="_blank">securely encrypted</a> <b>before</b> it leaves your machine.</p> <p> Lazarus Sync also allows you to <b>synchronize</b> your personal form data between every browser you install Lazarus on. <br>At home, at the office, on the laptop, all your web-form data, available to you anywhere.</p>',
  "options.sync.info.warning": 'Lazarus Sync is an optional new service, currently in beta. To keep using Lazarus Sync after the beta period ends, you will need to sign up for <a href="{url.proVersion}">Lazarus Pro</a>, now available at an an early adopter special rate.',
  "options.sync.moreInfo": 'For more information about Lazarus Sync, including <a href="{url.syncSecurity}" target="_blank">how secure we\'ve made it</a>, check out the <a href="{url.syncFAQ}" target="_blank">FAQ pages</a>.',
	"options.sync.email": "Email Address",
	"options.sync.password": "Lazarus Sync Password",
	"options.sync.resetPassword": "Forgotten your sync password?",
	"options.sync.enterPassword": "Enter Password",
	"options.sync.confirmPassword": "Confirm Password",
	"options.sync.login": "Login",
	"options.sync.loginToInterclue": "Login to Lazarus Sync",
	"options.sync.loggingIn": "logging in...",
	"options.sync.loggedIn": "logged in.",
	"options.sync.createAccount": "Create a New Sync Account",
	"options.sync.creatingAccount": "Creating account...",
	"options.sync.createdAccount": "New account created.",
	"options.sync.createAccountBtn": "Create Account",
  "options.sync.clearServerData.confirm": "Do you want to remove your private data currently stored on the sync server?",
	"options.sync.clearServerData.success": "Data removed from the sync server successfully",
  "options.sync.enterKey": "Enter your Lazarus Sync Key",
	"options.sync.key": "Sync Key",
	"options.sync.now": "Sync Now",
	"options.sync.setup": "Setup Sync",
	"options.sync.setup.btn": "Setup Sync...",
	"options.sync.server": "Sync Server URL",
	"options.sync.account": "Sync Account",
	"options.sync.account.created": "Account created",
	"options.sync.syncing": "Syncing database (this may take some time)...",
  "options.sync.syncInfo": 'Signed in as <span class="sync-email">{syncEmail}</span>.<br/>Last synced {lastSyncedStr}',
	"options.sync.success": "Database synced successfully.",
	"options.sync.loggedIn": "Logged in.",
	"options.sync.loginWarning": 'Sync is disabled, please <a id="sync-login-warning-link">log back in</a>',
	"options.sync.stopSyncing": "Stop syncing this browser",
	"options.sync.resetSyncDatabase": "Reset the data stored on the sync server",
	"options.sync.resetWarning": "This will delete all your forms saved on the sync server.\nThe forms on your local machine will remain intact and you should be able to re-sync them afterwards.\nAre you sure you want to do this?",
	"options.sync.resetSuccess": "Successfully reset the sync server database, do you want to re-sync this browser, or stop syncing for now?\n\nResync this browser??",
	"options.sync.instructions": "You'll need a Lazarus Sync Account before you can setup sync.",
	"options.sync.recreateAccount": "Sorry, but we need you to <a id=\"link-reenter-sync-info\" href=\"#\">re-enter your sync server details</a>",
  
  "options.updates.checkForBetaVersions": "Check for Beta versions?",
	"options.tests": "Tests",
	"options.runUnitTests": "Run Unit Tests",
  
  "error.accountReset": "Your password has been reset, please login using the new password",
  "error.emailRequired": "Email is required",
  "error.passwordRequired": "Password is required",
  "error.passwordsDoNotMatch": "Passwords do not match",
	"error.server": "Error: Sorry, an error occurred and the server cannot perform the required function. '{errMsg}'",
	"error.cannot.find.form": "Error: Cannot find form",
  "error.domain.required": "Domain is required",
  
  "btn.show.menu.tooltip": "Lazarus is saving this form. \nClick to recover previous versions",
  "error.passwords.do.not.match": "Your new passwords do not match",
  "password.set": "New password set",
  "password.removed": "Password removed",
  "error.server.unknown": "Server Error: Something went wrong and we were unable to complete the request, Sorry :(",
  "error.unable.to.load.encryption.key": "Unable to load encryption key",
  "error.wrong.password": "Incorrect password",
  "password.reset": "Password reset",
  
  "toolbar.tooltip.default": "Lazarus: Form Recovery",
  "toolbar.tooltip.loading": "Lazarus: Form Recovery: loading...",
  "toolbar.tooltip.disabled.user": "Lazarus has been disabled on '{domain}'",
  "toolbar.tooltip.disabled.protocol": "Sorry, Lazarus only works on ordinary web pages, and this one is special.",
  "toolbar.tooltip.disabled.platform": "Sorry, for security reasons, extensions are not allowed to alter pages on '{domain}'",
  "toolbar.tooltip.disabled.privateBrowsing": "Lazarus is disabled in private browsing mode",
  "toolbar.tooltip.syncMessages": "Lazarus: You have messages waiting, click to view",
}


